<?xml version="1.0" encoding="UTF-8" ?>
<Package name="20q" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="choice_sentences" src="behavior_1/Aldebaran/choice_sentences.xml" />
        <File name="HISTORY" src="lib/requests-2.9.1/HISTORY.rst" />
        <File name="LICENSE" src="lib/requests-2.9.1/LICENSE" />
        <File name="MANIFEST" src="lib/requests-2.9.1/MANIFEST.in" />
        <File name="NOTICE" src="lib/requests-2.9.1/NOTICE" />
        <File name="PKG-INFO" src="lib/requests-2.9.1/PKG-INFO" />
        <File name="README" src="lib/requests-2.9.1/README.rst" />
        <File name="PKG-INFO" src="lib/requests-2.9.1/requests.egg-info/PKG-INFO" />
        <File name="SOURCES" src="lib/requests-2.9.1/requests.egg-info/SOURCES.txt" />
        <File name="dependency_links" src="lib/requests-2.9.1/requests.egg-info/dependency_links.txt" />
        <File name="not-zip-safe" src="lib/requests-2.9.1/requests.egg-info/not-zip-safe" />
        <File name="requires" src="lib/requests-2.9.1/requests.egg-info/requires.txt" />
        <File name="top_level" src="lib/requests-2.9.1/requests.egg-info/top_level.txt" />
        <File name="__init__" src="lib/requests-2.9.1/requests/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/__init__.pyc" />
        <File name="adapters" src="lib/requests-2.9.1/requests/adapters.py" />
        <File name="adapters" src="lib/requests-2.9.1/requests/adapters.pyc" />
        <File name="api" src="lib/requests-2.9.1/requests/api.py" />
        <File name="api" src="lib/requests-2.9.1/requests/api.pyc" />
        <File name="auth" src="lib/requests-2.9.1/requests/auth.py" />
        <File name="auth" src="lib/requests-2.9.1/requests/auth.pyc" />
        <File name="cacert" src="lib/requests-2.9.1/requests/cacert.pem" />
        <File name="certs" src="lib/requests-2.9.1/requests/certs.py" />
        <File name="certs" src="lib/requests-2.9.1/requests/certs.pyc" />
        <File name="compat" src="lib/requests-2.9.1/requests/compat.py" />
        <File name="compat" src="lib/requests-2.9.1/requests/compat.pyc" />
        <File name="cookies" src="lib/requests-2.9.1/requests/cookies.py" />
        <File name="cookies" src="lib/requests-2.9.1/requests/cookies.pyc" />
        <File name="exceptions" src="lib/requests-2.9.1/requests/exceptions.py" />
        <File name="exceptions" src="lib/requests-2.9.1/requests/exceptions.pyc" />
        <File name="hooks" src="lib/requests-2.9.1/requests/hooks.py" />
        <File name="hooks" src="lib/requests-2.9.1/requests/hooks.pyc" />
        <File name="models" src="lib/requests-2.9.1/requests/models.py" />
        <File name="models" src="lib/requests-2.9.1/requests/models.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/__init__.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/chardet/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/chardet/__init__.pyc" />
        <File name="big5freq" src="lib/requests-2.9.1/requests/packages/chardet/big5freq.py" />
        <File name="big5prober" src="lib/requests-2.9.1/requests/packages/chardet/big5prober.py" />
        <File name="chardetect" src="lib/requests-2.9.1/requests/packages/chardet/chardetect.py" />
        <File name="chardistribution" src="lib/requests-2.9.1/requests/packages/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/requests-2.9.1/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/requests-2.9.1/requests/packages/chardet/charsetprober.py" />
        <File name="codingstatemachine" src="lib/requests-2.9.1/requests/packages/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/requests-2.9.1/requests/packages/chardet/compat.py" />
        <File name="constants" src="lib/requests-2.9.1/requests/packages/chardet/constants.py" />
        <File name="cp949prober" src="lib/requests-2.9.1/requests/packages/chardet/cp949prober.py" />
        <File name="escprober" src="lib/requests-2.9.1/requests/packages/chardet/escprober.py" />
        <File name="escsm" src="lib/requests-2.9.1/requests/packages/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/requests-2.9.1/requests/packages/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/requests-2.9.1/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/requests-2.9.1/requests/packages/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/requests-2.9.1/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/requests-2.9.1/requests/packages/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/requests-2.9.1/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/requests-2.9.1/requests/packages/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/requests-2.9.1/requests/packages/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/requests-2.9.1/requests/packages/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/requests-2.9.1/requests/packages/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/requests-2.9.1/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/requests-2.9.1/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/requests-2.9.1/requests/packages/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/requests-2.9.1/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/requests-2.9.1/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/requests-2.9.1/requests/packages/chardet/langthaimodel.py" />
        <File name="latin1prober" src="lib/requests-2.9.1/requests/packages/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/requests-2.9.1/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/requests-2.9.1/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/requests-2.9.1/requests/packages/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/requests-2.9.1/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/requests-2.9.1/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/requests-2.9.1/requests/packages/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/requests-2.9.1/requests/packages/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/requests-2.9.1/requests/packages/chardet/utf8prober.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/__init__.pyc" />
        <File name="_collections" src="lib/requests-2.9.1/requests/packages/urllib3/_collections.py" />
        <File name="_collections" src="lib/requests-2.9.1/requests/packages/urllib3/_collections.pyc" />
        <File name="connection" src="lib/requests-2.9.1/requests/packages/urllib3/connection.py" />
        <File name="connection" src="lib/requests-2.9.1/requests/packages/urllib3/connection.pyc" />
        <File name="connectionpool" src="lib/requests-2.9.1/requests/packages/urllib3/connectionpool.py" />
        <File name="connectionpool" src="lib/requests-2.9.1/requests/packages/urllib3/connectionpool.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/__init__.pyc" />
        <File name="appengine" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="pyopenssl" src="lib/requests-2.9.1/requests/packages/urllib3/contrib/pyopenssl.pyc" />
        <File name="exceptions" src="lib/requests-2.9.1/requests/packages/urllib3/exceptions.py" />
        <File name="exceptions" src="lib/requests-2.9.1/requests/packages/urllib3/exceptions.pyc" />
        <File name="fields" src="lib/requests-2.9.1/requests/packages/urllib3/fields.py" />
        <File name="fields" src="lib/requests-2.9.1/requests/packages/urllib3/fields.pyc" />
        <File name="filepost" src="lib/requests-2.9.1/requests/packages/urllib3/filepost.py" />
        <File name="filepost" src="lib/requests-2.9.1/requests/packages/urllib3/filepost.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/packages/__init__.pyc" />
        <File name="ordered_dict" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="ordered_dict" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ordered_dict.pyc" />
        <File name="six" src="lib/requests-2.9.1/requests/packages/urllib3/packages/six.py" />
        <File name="six" src="lib/requests-2.9.1/requests/packages/urllib3/packages/six.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ssl_match_hostname/__init__.pyc" />
        <File name="_implementation" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="_implementation" src="lib/requests-2.9.1/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.pyc" />
        <File name="poolmanager" src="lib/requests-2.9.1/requests/packages/urllib3/poolmanager.py" />
        <File name="poolmanager" src="lib/requests-2.9.1/requests/packages/urllib3/poolmanager.pyc" />
        <File name="request" src="lib/requests-2.9.1/requests/packages/urllib3/request.py" />
        <File name="request" src="lib/requests-2.9.1/requests/packages/urllib3/request.pyc" />
        <File name="response" src="lib/requests-2.9.1/requests/packages/urllib3/response.py" />
        <File name="response" src="lib/requests-2.9.1/requests/packages/urllib3/response.pyc" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/util/__init__.py" />
        <File name="__init__" src="lib/requests-2.9.1/requests/packages/urllib3/util/__init__.pyc" />
        <File name="connection" src="lib/requests-2.9.1/requests/packages/urllib3/util/connection.py" />
        <File name="connection" src="lib/requests-2.9.1/requests/packages/urllib3/util/connection.pyc" />
        <File name="request" src="lib/requests-2.9.1/requests/packages/urllib3/util/request.py" />
        <File name="request" src="lib/requests-2.9.1/requests/packages/urllib3/util/request.pyc" />
        <File name="response" src="lib/requests-2.9.1/requests/packages/urllib3/util/response.py" />
        <File name="response" src="lib/requests-2.9.1/requests/packages/urllib3/util/response.pyc" />
        <File name="retry" src="lib/requests-2.9.1/requests/packages/urllib3/util/retry.py" />
        <File name="retry" src="lib/requests-2.9.1/requests/packages/urllib3/util/retry.pyc" />
        <File name="ssl_" src="lib/requests-2.9.1/requests/packages/urllib3/util/ssl_.py" />
        <File name="ssl_" src="lib/requests-2.9.1/requests/packages/urllib3/util/ssl_.pyc" />
        <File name="timeout" src="lib/requests-2.9.1/requests/packages/urllib3/util/timeout.py" />
        <File name="timeout" src="lib/requests-2.9.1/requests/packages/urllib3/util/timeout.pyc" />
        <File name="url" src="lib/requests-2.9.1/requests/packages/urllib3/util/url.py" />
        <File name="url" src="lib/requests-2.9.1/requests/packages/urllib3/util/url.pyc" />
        <File name="sessions" src="lib/requests-2.9.1/requests/sessions.py" />
        <File name="sessions" src="lib/requests-2.9.1/requests/sessions.pyc" />
        <File name="status_codes" src="lib/requests-2.9.1/requests/status_codes.py" />
        <File name="status_codes" src="lib/requests-2.9.1/requests/status_codes.pyc" />
        <File name="structures" src="lib/requests-2.9.1/requests/structures.py" />
        <File name="structures" src="lib/requests-2.9.1/requests/structures.pyc" />
        <File name="utils" src="lib/requests-2.9.1/requests/utils.py" />
        <File name="utils" src="lib/requests-2.9.1/requests/utils.pyc" />
        <File name="requirements" src="lib/requests-2.9.1/requirements.txt" />
        <File name="setup" src="lib/requests-2.9.1/setup.cfg" />
        <File name="setup" src="lib/requests-2.9.1/setup.py" />
        <File name="test_requests" src="lib/requests-2.9.1/test_requests.py" />
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="api" src="lib/requests/api.py" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="cacert" src="lib/requests/cacert.pem" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="models" src="lib/requests/models.py" />
        <File name="__init__" src="lib/requests/packages/__init__.py" />
        <File name="__init__" src="lib/requests/packages/chardet/__init__.py" />
        <File name="big5freq" src="lib/requests/packages/chardet/big5freq.py" />
        <File name="big5prober" src="lib/requests/packages/chardet/big5prober.py" />
        <File name="chardetect" src="lib/requests/packages/chardet/chardetect.py" />
        <File name="chardistribution" src="lib/requests/packages/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/requests/packages/chardet/charsetprober.py" />
        <File name="codingstatemachine" src="lib/requests/packages/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/requests/packages/chardet/compat.py" />
        <File name="constants" src="lib/requests/packages/chardet/constants.py" />
        <File name="cp949prober" src="lib/requests/packages/chardet/cp949prober.py" />
        <File name="escprober" src="lib/requests/packages/chardet/escprober.py" />
        <File name="escsm" src="lib/requests/packages/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/requests/packages/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/requests/packages/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/requests/packages/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/requests/packages/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/requests/packages/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/requests/packages/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/requests/packages/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/requests/packages/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/requests/packages/chardet/langthaimodel.py" />
        <File name="latin1prober" src="lib/requests/packages/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/requests/packages/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/requests/packages/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/requests/packages/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/requests/packages/chardet/utf8prober.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/__init__.py" />
        <File name="_collections" src="lib/requests/packages/urllib3/_collections.py" />
        <File name="connection" src="lib/requests/packages/urllib3/connection.py" />
        <File name="connectionpool" src="lib/requests/packages/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/contrib/__init__.py" />
        <File name="appengine" src="lib/requests/packages/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="exceptions" src="lib/requests/packages/urllib3/exceptions.py" />
        <File name="fields" src="lib/requests/packages/urllib3/fields.py" />
        <File name="filepost" src="lib/requests/packages/urllib3/filepost.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/__init__.py" />
        <File name="ordered_dict" src="lib/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/requests/packages/urllib3/packages/six.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/requests/packages/urllib3/poolmanager.py" />
        <File name="request" src="lib/requests/packages/urllib3/request.py" />
        <File name="response" src="lib/requests/packages/urllib3/response.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/util/__init__.py" />
        <File name="connection" src="lib/requests/packages/urllib3/util/connection.py" />
        <File name="request" src="lib/requests/packages/urllib3/util/request.py" />
        <File name="response" src="lib/requests/packages/urllib3/util/response.py" />
        <File name="retry" src="lib/requests/packages/urllib3/util/retry.py" />
        <File name="ssl_" src="lib/requests/packages/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/requests/packages/urllib3/util/timeout.py" />
        <File name="url" src="lib/requests/packages/urllib3/util/url.py" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="utils" src="lib/requests/utils.py" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
